name: varadvani
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.4
  url_launcher: ^6.3.2
  dotted_line: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
  - assets/image/
  - assets/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  fonts:
    - family: Gotu
      fonts:
        - asset: assets/fonts/Gotu-Regular.ttf
          style: normal
    - family: Mukta_light
      fonts:
        - asset: assets/fonts/Mukta-Light.ttf
          style: normal
    - family: Mukta
      fonts:
        - asset: assets/fonts/Mukta-Regular.ttf
          style: normal
    - family: Mukta_medium
      fonts:
        - asset: assets/fonts/Mukta-Medium.ttf
          style: normal
    - family: Mukta_semibold
      fonts:
        - asset: assets/fonts/Mukta-SemiBold.ttf
          style: normal
